[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = "test"

[tool.isort]
line_length = 200

[tool.black]
line_length = 200